/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.tovot.example.lambda.pdf.renderer;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
